# permissions for end users to edit debugcontainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: debugcontainer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dbg-operator
    app.kubernetes.io/part-of: dbg-operator
    app.kubernetes.io/managed-by: kustomize
  name: debugcontainer-editor-role
rules:
- apiGroups:
  - sielert.com
  resources:
  - debugcontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sielert.com
  resources:
  - debugcontainers/status
  verbs:
  - get
